openapi: 3.1.0
info:
  title: Vehicle Registration API
  version: 1.0.0
  description: Lookup vehicle details via registration number (Plate).
paths:
  /vehicles/{registrationNumber}:
    get:
      summary: Get vehicle details by plate
      tags:
        - Vehicle
      operationId: getVehicleByPlate
      parameters:
        - name: registrationNumber
          in: path
          required: true
          description: The vehicle registration number (e.g., ABC1234)
          schema:
            type: string
            # FEATURE: Strict Regex Validation
            # Ensures only alphanumeric chars, 3-8 characters long
            pattern: '^[A-Z0-9]{3,8}$'
      responses:
        '200':
          description: Vehicle found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleDetail'
        '404':
          description: Vehicle not found

components:
  schemas:
    VehicleDetail:
      type: object
      required: [make, model, year, registration]
      properties:
        registration:
          type: string
        make:
          type: string
          example: "Tesla"
        model:
          type: string
          example: "Model 3"
        year:
          type: integer
          minimum: 1900
        engine:
          $ref: '#/components/schemas/EngineInfo'

    EngineInfo:
      type: object
      properties:
        type:
          type: string
          enum: [ELECTRIC, PETROL, DIESEL, HYBRID]
        horsepower:
          type: integer